name: fally
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Augmented Reality Plugins
  arkit_plugin: ^1.1.2
  flutter_map: ^6.1.0
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.5.3
  # Math Support
  vector_math: ^2.1.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Use ^3.0.0 or adjust based on compatibility

flutter:
  uses-material-design: true

  assets:
    - assets/images/forest_illustration.jpg
    - assets/images/logo.png
    - assets/images/map.jpg
    - assets/images/mapd.jpg

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700


